# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DSIHT_Cpp <- function(x, y, weight, ic_type, ic_scale, sequence, kappa, g_index, ic_coef) {
    .Call('_ADSIHT_DSIHT_Cpp', PACKAGE = 'ADSIHT', x, y, weight, ic_type, ic_scale, sequence, kappa, g_index, ic_coef)
}

DSIHT_Cpp_logit <- function(x, y, weight, ic_type, ic_scale, sequence, kappa, g_index, ic_coef) {
    .Call('_ADSIHT_DSIHT_Cpp_logit', PACKAGE = 'ADSIHT', x, y, weight, ic_type, ic_scale, sequence, kappa, g_index, ic_coef)
}

IWLS <- function(X, y, beta, p) {
    .Call('_ADSIHT_IWLS', PACKAGE = 'ADSIHT', X, y, beta, p)
}

